name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: noisemodelling
          POSTGRES_PASSWORD: noisemodelling
          POSTGRES_DB: noisemodelling_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      # Checkout the source code of the project
      - name: Checkout
        uses: actions/checkout@v4
      # Setup the jdk using version 11 of Adoptium Temurin
      - name: Setup java 11 using Adoptium Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Building
        run: mvn test package javadoc:test-javadoc javadoc:jar -B
      - name: Maven Deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        if: ${{ (env.MAVEN_USERNAME != null) && (github.ref == 'refs/heads/main') }}
        run: mvn clean deploy -B
      - name: Build NoiseModelling WebServer package with Maven
        run: mvn -B clean package -DskipTests
        working-directory: ./noisemodelling-scripts

      - name: Unzip webserver artifacts
        run: unzip target/NoiseModelling_*.zip -d NoiseModelling_WebServer
        working-directory: ./noisemodelling-scripts

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NoiseModelling_WebServer
          path: noisemodelling-scripts/NoiseModelling_WebServer/

